### PR TITLE
Added more configuration classes

### PR DESCRIPTION
**Pull request by amancevice**
* MoreForgivingConfiguration
* DropboxConfiguration
* MergedConfiguration

### CODE REVIEW

**Comment by ethanrowe** [comment]
Regarding bootstrapping without a `Mandrel.py` file:
- I think the functionality for having a fallback default bootstrap configuration, at a specific directory, is a good feature to offer.
- But I think it should be available as some utility function that can be invoked, rather than being tightly integrated into a particular class.

So, suppose you have some function you can call like `mandrel.bootstrap_at_directory(path)`, and it knows how to handle the case where the directory at `path` has a `Mandrel.py` file and the case where it does not.

Now there's no need for a `MoreForgivingConfiguration` class; instead, your application driver (not part of this project) might do something like:

```python
try:
    import mandrel.bootstrap
except mandrel.MissingBootstrapException:
    mandrel.bootstrap_at_path(os.getcwd())
```

This separates the operational concern of bootstrapping from the class itself.  If bootstrapping would work via normal means, the above will prefer that; but it will default to using the current working directory as your bootstrap base.

Another aspect of your `MoreForgivingConfiguration` class was that it would take the module's package directory and put that onto the search path.  That feels like an application-specific need so I would recommend having this be a subclass in your app and not part of mandrel proper.  If `mandrel` itself had the bootstrapping function described above, then its pretty easy for your app to do its own thing in the subclass without all the complexity of bootstrapping, so that's not a big lift for your app.

I think you can alter the config search path whenever you want, so there's no reason that the class needs to have bootstrapping behavior in order to influence the search path.  I wouldn't personally recommend having the class use its module directory in this way, but that's your business.

The `DropboxConfiguration` is specific to your application and not really applicable to `mandrel` itself; so I would make that subclass in your own app and not include it here.

I'll comment on the `MergedConfiguration` thing in a bit; I think that you may not need this if you use the existing classes differently.  I need to review first.

**Comment by ethanrowe** [comment]
I'm not positive it does exactly what you want, but it may be that if you make use of chaining, you'll get a behavior that works in place of making that `MergedConfiguration` class.

In the `mandrel.config.core.Configuration` class, look at the `*chain` that gets passed into `__init__()`, the `chained_get()` method, and the way `__getattr__()` uses `chained_get()`.

Depending on usage, this lets you compose configuration into a single entity.  It's only been used a little bit though I think it's reasonably well tested.

Suppose you have some base configuration, and then you have a few different separate configs that you might want to "merge into" that base config.

Rather than taking the base configuration and mutating it with the contents of the separate configs, you could instead create a configuration that has each of the others in order of most to least specific.

```python
conf = `Configuration({}, most_specific_config_obj, less_specific_config_obj, base_config_obj)`
# Would look for "foo" across those configs in order and return the first non-missing one.
print conf.foo
```

It's coarser in how things merge than is a recursive merge of dictionaries.  However, it may allow you to solve your problem more simply.

**Comment by amancevice** [comment]
I hear what you are saying with regards to the bootstrapping behavior; specifically the method you described `mandrel.bootstrap_at_path()`

I suppose that's easy enough to accomplish at the driver-level.

The issue I have with coding the `DropboxConfiguration` at the driver-level is that it means for every project I'll have to write the same again, instead of a simple subclass defining `NAME` and `DROPBOX`. Example:

```python
import mandrel.config
class MyConfig(mandrel.config.DropboxConfiguration, mandrel.config.MergedConfiguration):
    NAME = 'foo'
    DROPBOX = 'foo-app'
   # Automatically adds ~/Dropbox/Mandrel/foo-app/' to SEARCH_PATHS and merges with whatever else is found on the search path
```

**Comment by ethanrowe** [comment]
A few more things:

1. Regarding `DropboxConfiguration`:

    This class as you've implemented has nothing to do with dropbox and everything to do with some
    locations on the filesystem/environment that have forms of the word "dropbox" in them.  As it
    stands, it really is highly specific to your use case and pretty clearly doesn't belong in the general
    `mandrel` tool itself.

    Now, you could make this more generic and we could talk about a class that has some way of
    determining its own special path, and when instantiated, ensures that the class' special path is
    on the mandrel search path list.  I wouldn't necessarily recommend that, because the search path
    affects mandrel's behavior globally, so it's odd having the use of a particular class altering global
    behavior (rather than isolating things to that class' behavior).  But it would be general and we can
    at least consider its inclusion.  It would need to not rely on use-specific environment variables or
    paths; those things could be done via application-specific subclasses.

    I hear what you're saying about not wanting to duplicate your own subclass of this all over the
    place, and I agree that unifying such things in libraries is a good idea.  But it does not follow that
    mandrel itself is the right library for a pattern that is idiosyncratic to your application.  :)

2. Regarding bootstrapping without a `Mandrel.py` file:

    I went through this stuff and determined that it's actually fairly unpleasant and invasive to make the
    changes I was describing.  It was a mistake on my part to keep the logic and state of bootrapping
    in the `mandrel.bootstrap` module itself; I should have put it elsewhere and had `mandrel.bootstrap`
    rely upon it.

    But here we are.  I think at this point a reasonable approach would be to introduce a couple new
    environment variables.
    - `MANDREL_FILE` could be used to specify the path of the `Mandrel.py` file explicitly.
    - `MANDREL_DIRECTORY` could be used to specify the directory to use as the base path, without a `Mandrel.py` file.

    If `MANDREL_FILE` is non-empty, then the bootstrap searching function should split it and return
    the appropriate parts.

    If `MANDREL_DIRECTORY` is non-empty, then bootstrap searching function should return it with
    `None` as the file portion.

    The bootstrap file parsing function should skip the read/eval logic if the file portion is `None`.

    `MANDREL_FILE` overrules `MANDREL_DIRECTORY`.

    If we made those changes, then use of mandrel within python itself is essentially unchanged; you
    use environment variables if you want it to handle the case where there's no bootstrap file, or if
    you want to specify the bootstrap file explicitly rather than being tied to running things from a
    particular location in the file system.

    If it had those environment variables, that would solve your current bootstrapping flexibility needs,
    yes?

**Pull request closed without merging**
